
# Data Preprocessing for Machine Learning: Data Scaling
---
Data Scaling or Normalization: Assume we have a dataset with 2 columns. The values of one column are much larger than the values of the second column. The goal of data scaling is to scale the columns to be in the same range.

In [11]:
import numpy as np


## Activity for Data Scaling: Max_Min Scaler¶

In [15]:
# A two dimensional array (Matrix) X is given, write a function max_min_s that for each column:

# Obtains the minimum value of the column (min)
# Obtains the range of the column (range)
# For each value in the column, calculate the following: (value-min)/range

def min_max(x):
    return ((x - x.min(axis=0)) / (x.max(axis=0) - x.min(axis=0))).round()

X_train = np.array([[1000.0, 2.0], [1500.0, 3.0]])
print(min_max(X_train))

[[0. 0.]
 [1. 1.]]


In [17]:
# Let's use the Sklearn preprocessing package to do the same thing as our above function:

from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X_train)
print(X_minmax)

## Activity for Data Scaling: Standard Scaler
A two dimensional array (Matrix) X is given, write a function that for each column:  

In [19]:
# Obtain the mean for the column (mean)  
# Obtain the standard deviation for the column (std)  
# For each value in the column, calculate the following: (value - mean)/std  
# We will use breakout rooms in Zoom for group work!

def scalar_(x):
    return ( (x-x.mean(axis=0)) / (np.std(x, axis=0)))

print(scalar_(X_train))

[[-1. -1.]
 [ 1.  1.]]


## Lets use Sklearn preprecoessing package to do the same thing:¶


In [20]:
standard_scaler = preprocessing.StandardScaler()
X_ss = standard_scaler.fit_transform(X_train)
print(X_ss)

[[-1. -1.]
 [ 1.  1.]]
